### ISSUE TITLE
Make the script take extensions from a config file

### ISSUE THREAD

**Issue by prashantsengar** [prashantsengar/CleanPy#1]
Make the script take extensions and corresponding folder names from a config file so that it becomes more user-customizable.

Learn about config files [here](https://docs.python.org/3/library/configparser.html) and [here](https://www.geeksforgeeks.org/python-reading-ini-configuration-files/)

I want something like this:
[DEFAULT]
folderName = fileExtension(s)

Example:
cleanedDocs = ['pdf', 'docx', 'pptx', 'txt']
cleanedAudio = ['mp3', 'wav']
cleanedVideo = ['mp4', 'avi', 'mkv']

**Comment by sid779** [comment]
I would like to work on this.

**Comment by chavarera** [comment]
I would like to work on this.

**Comment by chavarera** [comment]
and i can also optimize the code to faster execution

**Comment by chavarera** [comment]
#8 Code cleaned and Optimized

**Comment by prashantsengar** [comment]
@chavarera #8 and #9 do not solve this issue

**Comment by skcy2001** [comment]
I want to work on this issue. I have made most efficient code for it. Also I can solve issue #20

**Comment by prashantsengar** [comment]
Sure @skcy2001

**Comment by skcy2001** [comment]
Check #10 . This issue has been solved.
