### ISSUE TITLE
(FLK-E111) Indentation is not a multiple of four

### ISSUE THREAD

**Issue by prashantsengar** [prashantsengar/CleanPy#26]
## Description
PEP8 recommends that Python code indentation be a multiple of four.

## Occurrences
There are 5 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/prashantsengar/CleanPy/issue/FLK-E111/occurrences/](https://deepsource.io/gh/prashantsengar/CleanPy/issue/FLK-E111/occurrences/)

**Comment by Abhi-Kmr2046** [comment]
Can I work on this?

**Comment by prashantsengar** [comment]
Sure @Abhi-Kmr2046
