### ISSUE TITLE
Clean up the code

### ISSUE THREAD

**Issue by prashantsengar** [prashantsengar/CleanPy#3]
The first step towards great code is clean code. 

Let's start by cleaning up the code. You will require basic Python knowledge and PEP guidelines. ([know what is PEP 8 ](https://www.python.org/dev/peps/pep-0008/))

Make the code more efficient, and more modular.

**Comment by sid779** [comment]
I would like to do this. Please assign it to me.

**Comment by sid779** [comment]
Thanks

**Comment by sid779** [comment]
Thanks

**Comment by sid779** [comment]
I ran the arrange.py once for weak arrange but none of the folders were created.
After running once it is giving file already exists error while I'm not able to see any folders anywhere.
`Traceback (most recent call last):`
`  File "arrange.py", line 15, in <module>`
`    makeFolders('pPDF')`
`  File "arrange.py", line 13, in makeFolders`
`    os.mkdir(f'.\\{f}')`
`FileExistsError: [Errno 17] File exists: '.\\pPDF'`

**Comment by prashantsengar** [comment]
@sid779 it was a small error because I was writing it in Windows. It will be fixed by very soon

**Comment by chavarera** [comment]
I would like to do this.

**Comment by prashantsengar** [comment]
@chavarera this issue is being worked on by @sid779 and someone else too. If you'd like, you can choose other issues to work on or create a new issue.

**Comment by chavarera** [comment]
ok

**Comment by sid779** [comment]
As @chavarera already created a pull request and did the work required I'll unassign myself. Please merge the pull request.

**Comment by chavarera** [comment]
why @prashantsengar  not merging pull requests

**Comment by sid779** [comment]
He will eventually, just relax and try to resolve other issues.
