### ISSUE TITLE
Warn users before running strong arrange

### ISSUE THREAD

**Issue by prashantsengar** [prashantsengar/CleanPy#32]
Strong arrange rearranges the files inside the subfolders as well. It might cause problems if you run strong arrange at home with admin permissions (C drive in Windows), it can even move important files.

It is required to warn users about it before running strong arrange.

In the strong arrange function, add an argument called `warn` with default value `True`.
In the function, check if the value of `warn` is set to be `True`, if yes, then print the following message:
_You are going to strong arrange the directory DIRECTORY_NAME. It will rearrange all the files in the subfolders as well. It might cause issues if you have added wrong extensions in the config.ini file and run the program in a sensitive directory. You still have 5 seconds to cancel it if you want to review anything. (Press Ctrl+C to abort)_

After the above message, add a sleep of 5 seconds and exit the function gracefully. You will need to handle the Ctrl+C exception thrown.

**Comment by BobinMathew** [comment]
Hi @prashantsengar, I have sent a PR for this issue.
Kindly check it and give feedback as I am a beginner. :smiley:
