### ISSUE TITLE
Print what files were moved

### ISSUE THREAD

**Issue by prashantsengar** [prashantsengar/CleanPy#4]
Currently, the script directly moves all the files and does not notify how many or what files were moved. We should tell the user how many files were moved or what files were moved.

**Format should be something like:**
x total files moved out of which y were docs, z were audio files, t were videos.

A simple dictionary can be used for this or you may use collections.Counter ([docs](https://docs.python.org/3/library/collections.html#collections.Counter), [pymotw](https://pymotw.com/2/collections/counter.html))

**Comment by chavarera** [comment]
I would like to work on it

**Comment by chavarera** [comment]
check it now all code is ready https://github.com/chavarera/CleanPy
